version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres 
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  # Add a health check
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres: # Set a dependency on the database container
        condition: service_healthy   # Wait for database to be healthy 
    volumes:
      - .:/app
      - /app/tmp

volumes:
  pgdata:
